### ISSUE TITLE
support multiple wifi networks

### ISSUE THREAD

**Issue by martinmurphy** [oe1wkl/Morserino-32#30]
I was thinking of adding support for multiple wifi networks
allow setting of up to 3 wifi settings in the config
and allowing choosing of the active config.

This would allow configuring of home network, phone hotspot, and another network, so Morserino-32 could be used at multiple locations easily.

Would you be interested in a PR?

**Comment by oe1wkl** [comment]
Yes, would be useful in some cases.

Willi

**Comment by oe1wkl** [comment]
Has been implemented.
