### ISSUE TITLE
A suggestion for Koch training mode:

### ISSUE THREAD

**Issue by Supermagnum** [oe1wkl/Morserino-32#36]
Training mode: First the program sends a series of K's in CW for 30 seconds while the character K is displayed. Then it repeats the procedure with the character M. 

When that is complete it sends a four characters group using K and M in random places without displaying the signs. It then waits for a four characters input using the  morse device, shows the characters you have gotten correct in green, the wrong ones in red. 

That continues until the user has gotten 90 % correct of a number of groups, then a new letter is introduced ( for example X ), it is sent for 30 seconds while the character is displayed.

 Then the lesson continues using the new character until 90% of groups is correct, a new character or prosign is introduced and the lessons continues until all characters are learned. 

Reference link:
https://github.com/Supermagnum/SuperKoch

**Comment by oe1wkl** [comment]
Thanks for the suggestion. I will give it some thought for future firmware version.

**Comment by Supermagnum** [comment]
> Thanks for the suggestion. I will give it some thought for future firmware version.

That would be great.
I hope that you did read my complete idea:
https://github.com/Supermagnum/SuperKoch
