### ISSUE TITLE
External paddle reversed

### ISSUE THREAD

**Issue by skydiveguy** [oe1wkl/Morserino-32#49]
I was running v4.0 and my external paddle was working fine.
After upgrading to 4.2.1 its now reversed.
I see that there was a bug fix release of 4.0.1 that supposedly fixed this but it seems that it broke mine.

I am using a CWMorse brand double paddle.

Perhaps there could be an option added to the software to let the end user choose the setting?

**Comment by oe1wkl** [comment]
Get a current version of the manual and look up the option "External Pol."! 

W

Von meinem Mobiltelefon gesendet

**Comment by skydiveguy** [comment]
Aha! I had the latest manual but didn't dig deep enough I guess.
You are a rockstar.
thank you for the fast response and also for maintaining this!
