### ISSUE TITLE
Additional characters 

### ISSUE THREAD

**Issue by Linus-007** [oe1wkl/Morserino-32#59]
This is a great code set and product (m32). It is great to see German character support. I speak English, Spanish, German and Dutch. I saw how the characters, numbers, punctuation, and etc. are coded. Can other characters be added to support Spanish and French, etc.?

**Comment by oe1wkl** [comment]
Adding additional character sets is a bit tricky, as often the same Morse code pattern is used for different characters, depending on the language.
Some languages would require really a lot of work, e.g. the Japanese character set, as these characters are not available currently in the font I am using, so separate fonts would have to be created.

You would need to add a „locale“ parameter, to display the characters you want. Can be done, but is considerable work.
Fortunately all the code is open source, so anyone can contribute whatever they think should be added! ;-)
This is not on my priority list right now, as in practice it is only International Morse Code that is being used in most cases for ham radio.


Willi Kraml
***@***.***
