### ISSUE TITLE
Output changes on scroll in KochTrainer->LearnNewChr

### ISSUE THREAD

**Issue by michaellass** [oe1wkl/Morserino-32#63]
In the mode "Learn New Chr" under "Koch Trainer", the output changes when it's being scrolled up. Normally, the "OK" or "ERR" is bold and separated by a space. When scrolling up in this mode, it changes to a regular font and the space gets lost:

![signal-2022-11-12-220507_002](https://user-images.githubusercontent.com/11042539/201494640-1dc607ed-ee2a-4cc3-bc69-f2fe31859bfc.jpeg)

**Comment by oe1wkl** [comment]
Thanks for bringing this to my attention. I put it on the list of To Do’s - hopefully I can find out what causes this strange behavior soon!

Willi

**Comment by michaellass** [comment]
I see this has been fixed in version 4.5 :slightly_smiling_face:
