### ISSUE TITLE
how to change uppercase?

### ISSUE THREAD

**Issue by JamesYoo01** [oe1wkl/Morserino-32#64]
Dear Morserino team
I want to see UPPERCASE.
Is it possible? 
Please be check it.
Thank you.

**Comment by oe1wkl** [comment]
Of course you can change almost everything in the source code.
Lower case was done on purpose, as it is easier to read (that’s why newspaper and books are printed in lower case).

Willi
OE1WKL

**Comment by JamesYoo01** [comment]
thank you for your relpy.
Asian CW are normally use UPPERCASE letter.
Thank you

**Comment by JamesYoo01** [comment]
Sorry.
Can someone compile an uppercase version?
Compiled on Arduino, but failed error related to LoRa occurs.
