### ISSUE TITLE
Koch lesson doesn't get saved

### ISSUE THREAD

**Issue by dhopfm** [oe1wkl/Morserino-32#70]
**Moserino board revision:** 3
**Morserino SW version:** 4.5.1
**Relevant preferences:** Koch Sequence: LCWO

**Issue description:** The current Koch lesson isn't being stored across restarts (HW switch).

**Steps to reproduce:**
1. Switch on Morserino
2. Navigate to Koch Trainer → Select Lesson
3. Take note of current setting (lesson number/letter), let's call it `n`
4. Change lesson number/setting to something else using the rotary encoder, let's call it `m`
5. Click rotary encoder to confirm setting and to return to menu
6. Switch off and on using the hardware switch
7. Navigate back to Koch Trainer → Select Lesson

**Expected result:** Morserino remember the changed setting, lesson is set to `m`.

**Actual result:** Morserino reverts to the old setting, `n`.

Please let me know if I can be of any help with debugging! And as always, many thanks for this great project, Willi and team! 73!

**Comment by oe1wkl** [comment]
I found the bug. Will prepare a maintenance release soon.

Willi
