### ISSUE TITLE
Echo Trainer does not regognize correct input after <err> corrections.

### ISSUE THREAD

**Issue by mherfurth** [oe1wkl/Morserino-32#72]
This does not always happen, but quite often. Seems to happen when sending very long <err> inputs (>8 Dits) and/or several `<err>`s, but i am not sure, what the exact trigger is to let this happen.

I have reproduced this in Koch Trainer with lesson 1 (m) activated and using the Echo Trainer.

What i get there as example:
`mmm OK`
`e<err>s<err>mmm ERR`

Can provide photos if this helps.

**Comment by oe1wkl** [comment]
resolved in version 5.1.2 (the ERR just acted as a backspace, now it is resetting the whole word.
