### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by hippieben** [oe1wkl/Morserino-32#75]
There are broken links in the readme.md for the Build Instructions.
Steps 2&3 point to invalid links for the Heltech module documentation and driver download.  Both result in a 404.
https://heltec-automation-docs.readthedocs.io/en/latest/general/establish_serial_connection.html
https://heltec-automation-docs.readthedocs.io/en/latest/esp32+arduino/quick_start.html

**Comment by oe1wkl** [comment]
There are new instruction available...
