### ISSUE TITLE
Heltec v3 - blank screen

### ISSUE THREAD

**Issue by fred777** [oe1wkl/Morserino-32#83]
Hi! I'm trying to get latest release (5.0.3) running on a Heltec Wifi Lora32 v3 board and was able to compile it out of the box with Heltec board definitions 0.0.9 and Heltec Esp32 library 1.1.5.

But after upload, the display will stay blank, no matter if I define BOARDVERSION  3 or 4 in morsedefs.h

Did anyone have success with a Heltec v3 board yet? I do not need all features, just want to use it as a simple CW trainer / keyer. No need for Wifi or Lora.

**Comment by ret-medic** [comment]
Hi Fred777,

I had the same question a couple of months back and Willy told me that only the v2 module would work with the current Morserino. I couldn't find a v2 module So I went ahead and ordered one from Willy at the Morserino store. It already comes programmed and has the newest firmware on the module, v5.03. The price was within a few dollars of the V3 module. When I received it, it plugged right in and worked like new. I hope this helps you out.

Robert
AG6LK

**Comment by ret-medic** [comment]
I hope it works out for you. If you get the chance let me know if it works. I may give it a try.

Thanks,73
Robert

**Comment by ret-medic** [comment]
That’s nice, you’ve done a great job so far. That’s where I lack is the programming.

You could try asking the Morserino group: https://morserino.groups.io/g/main
There’s a lot of smart guys there
________________________________

**Comment by AdamZiegler** [comment]
I am not sure how much room there is, but I bet an adapter could be made to re-wire pins to match the existing PCB board. It would require a small pcb, 4 rows of low profile pin headers, and some board to board u shaped pin connectors to connect  to the existing female in headers.

**Comment by rubienr** [comment]
> 1.) Get a working build toolchain / dev environment. I gave up Arduino IDE at some point and migrated the project to PlatformIO. This was a big relief, as it not only is using a more up-to-date esptool for flashing but it's also possible to precisely define library dependencies and other settings. This is my config:
 
Hi @fred777,

Great work! I can second that. In contrast to the rather rudimentary Arduino `.ino` projects, PIO is a great enrichment and an enhancement to almost any `.pio` project and very good way to go.
- It is easy to set up a project,
- simple to build,
- simple to implement and run tests (and debug by serial logs or debugger),
- a good candidate to run with Github actions pipeline,
- highly flexible for different MCUs/boards and
- supported by may platforms (Linux, ARM Linux, Mac, Windoze).
- It has a large community, is well documented, comes with flexible library management, good UI and CLI.
- It generates CMake projects, hence supported by any reasonable IDE.

PIO + a compile time configuration strategy, for example like the Marlin FW applies ([configuration.h/cnfiguration_adv.h](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.1.x/Marlin)) would make the project very versatile. The switch from an EOL board to another would not be any pain. If the companion board becomes pin incompatible, another board can be considered in the compile-time configuration. By this strategy [Marlin](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.1.x/Marlin/src/pins) achieves the support of many boards + periphery + HW/FW-feature combinations.
