### ISSUE TITLE
pushbutton switch defective

### ISSUE THREAD

**Issue by dylanbeaudette** [oe1wkl/Morserino-32#87]
Thank you for this wonderful kit. Everything works as expected except the red pushbutton switch is defective. Something is wrong with the mechanism or spring. How can I find a suitable replacement?

**Comment by oe1wkl** [comment]
This is not an issue that can be dealt with on GitHub.

**Comment by oe1wkl** [comment]
Please write an email to info@morserino.info. GitHub issues are for firmware bugs or feature requests.

**Comment by dylanbeaudette** [comment]
Thanks. I couldn't find a suitable email on the website.

**Comment by oe1wkl** [comment]
when you bought the kit, you got several emails, right? why not use that address??please mail your request to ***@***.*** meinem 🍎 Telefon gesendetAm 17.12.2023 um 20:17 schrieb Dylan Beaudette ***@***.***>:﻿
Thanks. I couldn't find a suitable email on the website.

**Comment by oe1wkl** [comment]
GitHub does not show email addresses.
I need your email  addressto je able to solve your problem...

write to.
info (at-sign) morserino dot info.

W

**Comment by oe1wkl** [comment]
another option is to contact me through the groups.io morserino user group (which is the best way to get support, anyway).
W
