### ISSUE TITLE
Problem mit dem lora TRX

### ISSUE THREAD

**Issue by DC8CH** [oe1wkl/Morserino-32#95]
Im Modus LoraTRX blockiert der Empfänger bei Empfang und zeigt das empfangene Zeichen als Dauerlauf an. Es werden keine weiteren Zeichen empfangen. Senden funktioniert weiterhin allerdings ohne Anzeige.

Gibt es dafür Abhilfe?

Hardware ver1 
Software 5.1.1

beste Grüße 
Carsten

https://github.com/oe1wkl/Morserino-32/assets/161219167/e3192ec6-b4d3-41f5-9166-ba9840747cd2

**Comment by oe1wkl** [comment]
So ein Problem wurde noch nie beobachtet... ev ein Hardwareproblem?Wieweit ist es reproduzierbar?WilliOE1WKLVon meinem Mobiltelefon gesendetAm 15.04.2024 um 17:33 schrieb DC8CH ***@***.***>:﻿
Im Modus LoraTRX blockiert der Empfänger bei Empfang und zeigt das empfangene Zeichen als Dauerlauf an. Es werden keine weiteren Zeichen empfangen. Senden funktioniert weiterhin allerdings ohne Anzeige.
Gibt es dafür Abhilfe?
Hardware ver1
Software 5.1.1
beste Grüße
Carsten
https://github.com/oe1wkl/Morserino-32/assets/161219167/e3192ec6-b4d3-41f5-9166-ba9840747cd2

**Comment by DC8CH** [comment]
Dieses Problem tritt immer beim Empfang auf, wir haben schon probiert ob vllt Zuviel Leistung angekommen ist. Das war nicht der Fall für den Gegenvorschlag haben wir in einen Dummyload gesendet und auf den anderen Empfänger ebenfalls einen dumyload gesetzt. Der Fehler trat nur auf meinem moserino auf, der andere mit gleicher Firmware, aber hardware v2 klappt einwandfrei. Ansonsten funktioniert der morserino einwandfrei.Von meinem iPhone gesendetAm 15.04.2024 um 17:37 schrieb oe1wkl ***@***.***>:﻿
So ein Problem wurde noch nie beobachtet... ev ein Hardwareproblem?Wieweit ist es reproduzierbar?WilliOE1WKLVon meinem Mobiltelefon gesendetAm 15.04.2024 um 17:33 schrieb DC8CH ***@***.***>:﻿

Im Modus LoraTRX blockiert der Empfänger bei Empfang und zeigt das empfangene Zeichen als Dauerlauf an. Es werden keine weiteren Zeichen empfangen. Senden funktioniert weiterhin allerdings ohne Anzeige.

Gibt es dafür Abhilfe?

Hardware ver1

Software 5.1.1

beste Grüße

Carsten

https://github.com/oe1wkl/Morserino-32/assets/161219167/e3192ec6-b4d3-41f5-9166-ba9840747cd2

**Comment by oe1wkl** [comment]
Sieht mir eher nach einem defekten LoRa Empfänger aus....WilliVon meinem Mobiltelefon gesendetAm 15.04.2024 um 17:52 schrieb DC8CH ***@***.***>:﻿
Dieses Problem tritt immer beim Empfang auf, wir haben schon probiert ob vllt Zuviel Leistung angekommen ist. Das war nicht der Fall für den Gegenvorschlag haben wir in einen Dummyload gesendet und auf den anderen Empfänger ebenfalls einen dumyload gesetzt. Der Fehler trat nur auf meinem moserino auf, der andere mit gleicher Firmware, aber hardware v2 klappt einwandfrei. Ansonsten funktioniert der morserino einwandfrei.Von meinem iPhone gesendetAm 15.04.2024 um 17:37 schrieb oe1wkl ***@***.***>:﻿

So ein Problem wurde noch nie beobachtet... ev ein Hardwareproblem?Wieweit ist es reproduzierbar?WilliOE1WKLVon meinem Mobiltelefon gesendetAm 15.04.2024 um 17:33 schrieb DC8CH ***@***.***>:﻿



Im Modus LoraTRX blockiert der Empfänger bei Empfang und zeigt das empfangene Zeichen als Dauerlauf an. Es werden keine weiteren Zeichen empfangen. Senden funktioniert weiterhin allerdings ohne Anzeige.



Gibt es dafür Abhilfe?



Hardware ver1



Software 5.1.1



beste Grüße



Carsten



https://github.com/oe1wkl/Morserino-32/assets/161219167/e3192ec6-b4d3-41f5-9166-ba9840747cd2

**Comment by oe1wkl** [comment]
Apparently not a software issue, hence closing this issue.

**Comment by DC8CH** [comment]
Danke fürs prüfen! Von meinem iPhone gesendetAm 16.04.2024 um 16:57 schrieb oe1wkl ***@***.***>:﻿
Closed #95 as completed.
