### ISSUE TITLE
Probleme mit dem Einstellrädchen

### ISSUE THREAD

**Issue by Juergen2107** [oe1wkl/Morserino-32#99]
Hallo,
Mein Einstellrädchen funktioniert plötzlich nicht mehr.
Was tun ?
73 de Juergen DL2JHK

**Comment by oe1wkl** [comment]
Gar nicht? Oder nur der Drucktaster? Oder nur der Drehencoder?

Am wahrscheinlichsten ist, dass eine Lötstelle den Geist aufgegeben hat. Ich würde alle 5 Lötpads des Encoders gründlich nachlöten….

73

Willi

**Comment by Juergen2107** [comment]
Danke Willi, ich glaube das ist es.Herzliche GrüsseJürgen --Gesendet mit der GMX Mail AppAm 03.09.24, 15:15 schrieb oe1wkl ***@***.***>:

   Gar nicht? Oder nur der Drucktaster? Oder nur der Drehencoder? 
  
  
   Am wahrscheinlichsten ist, dass eine Lötstelle den Geist aufgegeben hat. Ich würde alle 5 Lötpads des Encoders gründlich nachlöten…. 
  
  
   73 
  
  
   Willi

**Comment by Juergen2107** [comment]
Dear Willi,

 

Es war wie du sagtest. Besten Dank !

 

Andere Frage:

 

Könnte man den Sensorkopf

 

 <https://www.bamatech.net/tastenzubehoer/sensorkopf-komplett.html> https://www.bamatech.net/tastenzubehoer/sensorkopf-komplett.html

 

irgendwie mit dem Morserino verbinden ?

 

Herzlichen Danke für deine Hilfe.

 

73 de Juergen 

DL2JHK, Berlin

 

 

 

 

Von: oe1wkl ***@***.***> 
Gesendet: Dienstag, 3. September 2024 15:15
An: oe1wkl/Morserino-32 ***@***.***>
Cc: Juergen2107 ***@***.***>; Author ***@***.***>
Betreff: Re: [oe1wkl/Morserino-32] Probleme mit dem Einstellrädchen (Issue #99)

 

Gar nicht? Oder nur der Drucktaster? Oder nur der Drehencoder? 

Am wahrscheinlichsten ist, dass eine Lötstelle den Geist aufgegeben hat. Ich würde alle 5 Lötpads des Encoders gründlich nachlöten…. 

73 

Willi

**Comment by oe1wkl** [comment]
Closed

**Comment by Juergen2107** [comment]
Dear Harald,

 

Many txs. How can I connect it with the Morserino ? Which pins on J1 and J2 do I have to use ?

 

73 de Juergen, DL2JHK

 

Von: Harald Klein ***@***.***> 
Gesendet: Mittwoch, 6. November 2024 13:48
An: oe1wkl/Morserino-32 ***@***.***>
Cc: Juergen2107 ***@***.***>; Author ***@***.***>
Betreff: Re: [oe1wkl/Morserino-32] Probleme mit dem Einstellrädchen (Issue #99)

 

The BaMaTech sensorhead is working fine with the ESP32 touch pins: https://youtu.be/djfCpwT8nyQ

**Comment by haklein** [comment]
Be aware that I've tested this with an ESP32-S3, the heltec v2 board on the Morserino is an older variant (with 8bit touch sensor instead of 16 bit). Still I'd suppose that it should work fine (it's just metal contacts for the touch pins after all..). You'd connect it to the touch pins as per schematics, PIN2 and PIN12 - https://github.com/oe1wkl/Morserino-32/blob/master/Documentation/Hardware/2nd_edition/schematics.pdf

**Comment by Juergen2107** [comment]
Txs Harald, I’ll try to do so.

 

Von: Harald Klein ***@***.***> 
Gesendet: Mittwoch, 6. November 2024 14:13
An: oe1wkl/Morserino-32 ***@***.***>
Cc: Juergen2107 ***@***.***>; Author ***@***.***>
Betreff: Re: [oe1wkl/Morserino-32] Probleme mit dem Einstellrädchen (Issue #99)

 

Be aware that I've tested this with an ESP32-S3, the heltec v2 board on the Morserino is an older variant (with 8bit touch sensor instead of 16 bit). Still I'd suppose that it should work fine (it's just metal contacts for the touch pins after all..). You'd connect it to the touch pins as per schematics, PIN2 and PIN12 - https://github.com/oe1wkl/Morserino-32/blob/master/Documentation/Hardware/2nd_edition/schematics.pdf

**Comment by oe1wkl** [comment]
Somehow this is quite interesting, but unfortunately it is off topic ;-) keine Probleme mit dem Einstellrädchen, oder?

**Comment by Juergen2107** [comment]
Nein, kalte Lötstelle beseitigt.Danke !!--Gesendet mit der GMX Mail AppAm 07.11.24, 09:19 schrieb oe1wkl ***@***.***>:

Somehow this is quite interesting, but unfortunately it is off topic ;-) keine Probleme mit dem Einstellrädchen, oder?
